export const externalPathsLib = {
   '@typhonjs-fvtt/svelte/action': '/modules/typhonjs/remote/svelte/action.js',
   '@typhonjs-fvtt/svelte/animate': '/modules/typhonjs/remote/svelte/animate.js',
   '@typhonjs-fvtt/svelte/animate/action': '/modules/typhonjs/remote/svelte/animate/action.js',
   '@typhonjs-fvtt/svelte/application': '/modules/typhonjs/remote/svelte/application.js',
   '@typhonjs-fvtt/svelte/application/dialog': '/modules/typhonjs/remote/svelte/application/dialog.js',
   '@typhonjs-fvtt/svelte/application/legacy': '/modules/typhonjs/remote/svelte/application/legacy.js',
   '@typhonjs-fvtt/svelte/component/core': '/modules/typhonjs/remote/svelte/component/core.js',
   '@typhonjs-fvtt/svelte/component/dialog': '/modules/typhonjs/remote/svelte/component/dialog.js',
   '@typhonjs-fvtt/svelte/gsap': '/modules/typhonjs/remote/svelte/gsap.js',
   '@typhonjs-fvtt/svelte/handler': '/modules/typhonjs/remote/svelte/handler.js',
   '@typhonjs-fvtt/svelte/helper': '/modules/typhonjs/remote/svelte/helper.js',
   '@typhonjs-fvtt/svelte/math': '/modules/typhonjs/remote/svelte/math.js',
   '@typhonjs-fvtt/svelte/plugin/data': '/modules/typhonjs/remote/svelte/plugin/data.js',
   '@typhonjs-fvtt/svelte/plugin/system': '/modules/typhonjs/remote/svelte/plugin/system.js',
   '@typhonjs-fvtt/svelte/store': '/modules/typhonjs/remote/svelte/store.js',
   '@typhonjs-fvtt/svelte/store/document': '/modules/typhonjs/remote/svelte/store/document.js',
   '@typhonjs-fvtt/svelte/store/dom': '/modules/typhonjs/remote/svelte/store/dom.js',
   '@typhonjs-fvtt/svelte/store/position': '/modules/typhonjs/remote/svelte/store/position.js',
   '@typhonjs-fvtt/svelte/store/reducer': '/modules/typhonjs/remote/svelte/store/reducer.js',
   '@typhonjs-fvtt/svelte/transition': '/modules/typhonjs/remote/svelte/transition.js',
   '@typhonjs-fvtt/svelte/util': '/modules/typhonjs/remote/svelte/util.js',

   '@typhonjs-plugin/manager': '/modules/typhonjs/remote/plugin/manager.js',

   'chroma-js': '/modules/typhonjs/remote/color/chroma.js',

   'colord': '/modules/typhonjs/remote/color/colord/index.js',
   'colord/plugins/a11y': '/modules/typhonjs/remote/color/colord/plugins/a11y.js',
   'colord/plugins/cmyk': '/modules/typhonjs/remote/color/colord/plugins/cmyk.js',
   'colord/plugins/harmonies': '/modules/typhonjs/remote/color/colord/plugins/harmonies.js',
   'colord/plugins/hwb': '/modules/typhonjs/remote/color/colord/plugins/hwb.js',
   'colord/plugins/lab': '/modules/typhonjs/remote/color/colord/plugins/lab.js',
   'colord/plugins/lch': '/modules/typhonjs/remote/color/colord/plugins/lch.js',
   'colord/plugins/minify': '/modules/typhonjs/remote/color/colord/plugins/minify.js',
   'colord/plugins/mix': '/modules/typhonjs/remote/color/colord/plugins/mix.js',
   'colord/plugins/names': '/modules/typhonjs/remote/color/colord/plugins/names.js',
   'colord/plugins/xyz': '/modules/typhonjs/remote/color/colord/plugins/xyz.js',

   'json5': '/modules/typhonjs/remote/json/json5.js',

   'svelte': '/modules/typhonjs/remote/svelte/index.js',
   'svelte/animate': '/modules/typhonjs/remote/svelte/animate.js',
   'svelte/easing': '/modules/typhonjs/remote/svelte/easing.js',
   'svelte/internal': '/modules/typhonjs/remote/svelte/internal.js',
   'svelte/motion': '/modules/typhonjs/remote/svelte/motion.js',
   'svelte/store': '/modules/typhonjs/remote/svelte/store.js',
   'svelte/transition': '/modules/typhonjs/remote/svelte/transition.js'
};