export const externalPathsNPM = {
   '@typhonjs-fvtt/svelte/application': '@typhonjs-fvtt/runtime/svelte/application',
   '@typhonjs-fvtt/svelte/component/application': '@typhonjs-fvtt/runtime/svelte/component/application',
   '@typhonjs-fvtt/svelte/component/internal': '@typhonjs-fvtt/runtime/svelte/component/internal',
   '@typhonjs-fvtt/svelte/gsap': '@typhonjs-fvtt/runtime/svelte/gsap',
   '@typhonjs-fvtt/svelte/gsap/plugin': '@typhonjs-fvtt/runtime/svelte/gsap/plugin',
   '@typhonjs-fvtt/svelte/gsap/plugin/bonus': '@typhonjs-fvtt/runtime/svelte/gsap/plugin/bonus',
   '@typhonjs-fvtt/svelte/store/fvtt': '@typhonjs-fvtt/runtime/svelte/store/fvtt',
   '@typhonjs-fvtt/svelte/store/fvtt/document': '@typhonjs-fvtt/runtime/svelte/store/fvtt/document',
   '@typhonjs-fvtt/svelte/store/fvtt/settings': '@typhonjs-fvtt/runtime/svelte/store/fvtt/settings',
   '@typhonjs-fvtt/svelte/store/fvtt/settings/world': '@typhonjs-fvtt/runtime/svelte/store/fvtt/settings/world',

   '@typhonjs-svelte/runtime-base/data/color/colord': '@typhonjs-fvtt/runtime/data/color/colord',
   '@typhonjs-svelte/runtime-base/data/compress': '@typhonjs-fvtt/runtime/data/compress',
   '@typhonjs-svelte/runtime-base/data/format/base64': '@typhonjs-fvtt/runtime/data/format/base64',
   '@typhonjs-svelte/runtime-base/data/format/jsonc': '@typhonjs-fvtt/runtime/data/format/jsonc',
   '@typhonjs-svelte/runtime-base/data/format/json5': '@typhonjs-fvtt/runtime/data/format/json5',
   '@typhonjs-svelte/runtime-base/data/format/msgpack': '@typhonjs-fvtt/runtime/data/format/msgpack',
   '@typhonjs-svelte/runtime-base/data/format/msgpack/compress': '@typhonjs-fvtt/runtime/data/format/msgpack/compress',
   '@typhonjs-svelte/runtime-base/data/format/unicode': '@typhonjs-fvtt/runtime/data/format/unicode',
   '@typhonjs-svelte/runtime-base/data/struct/cache/quick-lru': '@typhonjs-fvtt/runtime/data/struct/cache/quick-lru',
   '@typhonjs-svelte/runtime-base/data/struct/hash/array': '@typhonjs-fvtt/runtime/data/struct/hash/array',
   '@typhonjs-svelte/runtime-base/data/struct/search/trie': '@typhonjs-fvtt/runtime/data/struct/search/trie',
   '@typhonjs-svelte/runtime-base/data/struct/search/trie/query': '@typhonjs-fvtt/runtime/data/struct/search/trie/query',
   '@typhonjs-svelte/runtime-base/math/gl-matrix': '@typhonjs-fvtt/runtime/math/gl-matrix',
   '@typhonjs-svelte/runtime-base/math/interpolate': '@typhonjs-fvtt/runtime/math/interpolate',
   '@typhonjs-svelte/runtime-base/math/physics': '@typhonjs-fvtt/runtime/math/physics',
   '@typhonjs-svelte/runtime-base/math/util': '@typhonjs-fvtt/runtime/math/util',
   '@typhonjs-svelte/runtime-base/plugin/manager': '@typhonjs-fvtt/runtime/plugin/manager',
   '@typhonjs-svelte/runtime-base/plugin/manager/eventbus': '@typhonjs-fvtt/runtime/plugin/manager/eventbus',
   '@typhonjs-svelte/runtime-base/plugin/manager/eventbus/buses': '@typhonjs-fvtt/runtime/plugin/manager/eventbus/buses',
   '@typhonjs-svelte/runtime-base/svelte/action/animate': '@typhonjs-fvtt/runtime/svelte/action/animate',
   '@typhonjs-svelte/runtime-base/svelte/action/dom/focus': '@typhonjs-fvtt/runtime/svelte/action/dom/focus',
   '@typhonjs-svelte/runtime-base/svelte/action/dom/observer': '@typhonjs-fvtt/runtime/svelte/action/dom/observer',
   '@typhonjs-svelte/runtime-base/svelte/action/dom/properties': '@typhonjs-fvtt/runtime/svelte/action/dom/properties',
   '@typhonjs-svelte/runtime-base/svelte/action/dom/style': '@typhonjs-fvtt/runtime/svelte/action/dom/style',
   '@typhonjs-svelte/runtime-base/svelte/action/util': '@typhonjs-fvtt/runtime/svelte/action/util',
   '@typhonjs-svelte/runtime-base/svelte/animate': '@typhonjs-fvtt/runtime/svelte/animate',
   '@typhonjs-svelte/runtime-base/svelte/easing': '@typhonjs-fvtt/runtime/svelte/easing',
   '@typhonjs-svelte/runtime-base/svelte/store/dom': '@typhonjs-fvtt/runtime/svelte/store/dom',
   '@typhonjs-svelte/runtime-base/svelte/store/position': '@typhonjs-fvtt/runtime/svelte/store/position',
   '@typhonjs-svelte/runtime-base/svelte/store/reducer': '@typhonjs-fvtt/runtime/svelte/store/reducer',
   '@typhonjs-svelte/runtime-base/svelte/store/util': '@typhonjs-fvtt/runtime/svelte/store/util',
   '@typhonjs-svelte/runtime-base/svelte/store/web-storage': '@typhonjs-fvtt/runtime/svelte/store/web-storage',
   '@typhonjs-svelte/runtime-base/svelte/store/web-storage/msgpack': '@typhonjs-fvtt/runtime/svelte/store/web-storage/msgpack',
   '@typhonjs-svelte/runtime-base/svelte/store/writable-derived': '@typhonjs-fvtt/runtime/svelte/store/writable-derived',
   '@typhonjs-svelte/runtime-base/svelte/transition': '@typhonjs-fvtt/runtime/svelte/transition',
   '@typhonjs-svelte/runtime-base/svelte/util': '@typhonjs-fvtt/runtime/svelte/util',
   '@typhonjs-svelte/runtime-base/util': '@typhonjs-fvtt/runtime/util',
   '@typhonjs-svelte/runtime-base/util/a11y': '@typhonjs-fvtt/runtime/util/a11y',
   '@typhonjs-svelte/runtime-base/util/animate': '@typhonjs-fvtt/runtime/util/animate',
   '@typhonjs-svelte/runtime-base/util/async': '@typhonjs-fvtt/runtime/util/async',
   '@typhonjs-svelte/runtime-base/util/browser': '@typhonjs-fvtt/runtime/util/browser',
   '@typhonjs-svelte/runtime-base/util/dom/layout': '@typhonjs-fvtt/runtime/util/dom/layout',
   '@typhonjs-svelte/runtime-base/util/dom/observer': '@typhonjs-fvtt/runtime/util/dom/observer',
   '@typhonjs-svelte/runtime-base/util/dom/style': '@typhonjs-fvtt/runtime/util/dom/style',
   '@typhonjs-svelte/runtime-base/util/dom/tinykeys': '@typhonjs-fvtt/runtime/util/dom/tinykeys',
   '@typhonjs-svelte/runtime-base/util/i18n': '@typhonjs-fvtt/runtime/util/i18n',
   '@typhonjs-svelte/runtime-base/util/loader-module': '@typhonjs-fvtt/runtime/util/loader-module',
   '@typhonjs-svelte/runtime-base/util/object': '@typhonjs-fvtt/runtime/util/object',
   '@typhonjs-svelte/runtime-base/util/store': '@typhonjs-fvtt/runtime/util/store',

   // Special handling for local include of FVTT i18n implementation.
   '@typhonjs-fvtt/runtime/util/i18n': '@typhonjs-fvtt/runtime/util/i18n',

   // Exclude as external, but do not translate module references.
   'svelte': 'svelte',
   'svelte/animate': 'svelte/animate',
   'svelte/easing': 'svelte/easing',
   'svelte/internal': 'svelte/internal',
   'svelte/motion': 'svelte/motion',
   'svelte/store': 'svelte/store',
   'svelte/transition': 'svelte/transition'
};
