export const externalPathsNPM = {
   '@typhonjs-fvtt/svelte/action': '@typhonjs-fvtt/runtime/svelte/action',
   '@typhonjs-fvtt/svelte/action/dom': '@typhonjs-fvtt/runtime/svelte/action/dom',
   '@typhonjs-fvtt/svelte/animate': '@typhonjs-fvtt/runtime/svelte/animate',
   '@typhonjs-fvtt/svelte/animate/action': '@typhonjs-fvtt/runtime/svelte/animate/action',
   '@typhonjs-fvtt/svelte/application': '@typhonjs-fvtt/runtime/svelte/application',
   '@typhonjs-fvtt/svelte/application/dialog': '@typhonjs-fvtt/runtime/svelte/application/dialog',
   '@typhonjs-fvtt/svelte/application/legacy': '@typhonjs-fvtt/runtime/svelte/application/legacy',
   '@typhonjs-fvtt/svelte/component/core': '@typhonjs-fvtt/runtime/svelte/component/core',
   '@typhonjs-fvtt/svelte/component/dialog': '@typhonjs-fvtt/runtime/svelte/component/dialog',
   '@typhonjs-fvtt/svelte/gsap': '@typhonjs-fvtt/runtime/svelte/gsap',
   '@typhonjs-fvtt/svelte/gsap/plugin': '@typhonjs-fvtt/runtime/svelte/gsap/plugin',
   '@typhonjs-fvtt/svelte/gsap/plugin/bonus': '@typhonjs-fvtt/runtime/svelte/gsap/plugin/bonus',
   '@typhonjs-fvtt/svelte/handler': '@typhonjs-fvtt/runtime/svelte/handler',
   '@typhonjs-fvtt/svelte/helper': '@typhonjs-fvtt/runtime/svelte/helper',
   '@typhonjs-fvtt/svelte/math': '@typhonjs-fvtt/runtime/svelte/math',
   '@typhonjs-fvtt/svelte/math/gl-matrix': '@typhonjs-fvtt/runtime/svelte/math/gl-matrix',
   '@typhonjs-fvtt/svelte/store': '@typhonjs-fvtt/runtime/svelte/store',
   '@typhonjs-fvtt/svelte/store/document': '@typhonjs-fvtt/runtime/svelte/store/document',
   '@typhonjs-fvtt/svelte/store/dom': '@typhonjs-fvtt/runtime/svelte/store/dom',
   '@typhonjs-fvtt/svelte/store/position': '@typhonjs-fvtt/runtime/svelte/store/position',
   '@typhonjs-fvtt/svelte/store/reducer': '@typhonjs-fvtt/runtime/svelte/store/reducer',
   '@typhonjs-fvtt/svelte/store/storage/web': '@typhonjs-fvtt/runtime/svelte/store/storage/web',
   '@typhonjs-fvtt/svelte/store/storage/web/plugin': '@typhonjs-fvtt/runtime/svelte/store/storage/web/plugin',
   '@typhonjs-fvtt/svelte/transition': '@typhonjs-fvtt/runtime/svelte/transition',
   '@typhonjs-fvtt/svelte/util': '@typhonjs-fvtt/runtime/svelte/util',

   '@typhonjs-plugin/manager': '@typhonjs-fvtt/runtime/plugin/manager',

   'colord': '@typhonjs-fvtt/runtime/color/colord',
   'colord/plugins/a11y': '@typhonjs-fvtt/runtime/color/colord/plugins/a11y',
   'colord/plugins/cmyk': '@typhonjs-fvtt/runtime/color/colord/plugins/cmyk',
   'colord/plugins/harmonies': '@typhonjs-fvtt/runtime/color/colord/plugins/harmonies',
   'colord/plugins/hwb': '@typhonjs-fvtt/runtime/color/colord/plugins/hwb',
   'colord/plugins/lab': '@typhonjs-fvtt/runtime/color/colord/plugins/lab',
   'colord/plugins/lch': '@typhonjs-fvtt/runtime/color/colord/plugins/lch',
   'colord/plugins/minify': '@typhonjs-fvtt/runtime/color/colord/plugins/minify',
   'colord/plugins/mix': '@typhonjs-fvtt/runtime/color/colord/plugins/mix',
   'colord/plugins/names': '@typhonjs-fvtt/runtime/color/colord/plugins/names',
   'colord/plugins/xyz': '@typhonjs-fvtt/runtime/color/colord/plugins/xyz',

   'json5': '@typhonjs-fvtt/runtime/json/json5',

   // Exclude as external, but do not translate module references.
   'svelte': 'svelte',
   'svelte/animate': 'svelte/animate',
   'svelte/easing': 'svelte/easing',
   'svelte/internal': 'svelte/internal',
   'svelte/motion': 'svelte/motion',
   'svelte/store': 'svelte/store',
   'svelte/transition': 'svelte/transition'
};